apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
data:
  SERVER_PORT: "8080"
  POSTGRES_HOST: "postgres-member-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "member"
  POSTGRES_USER: "admin"
