apiVersion: v1
kind: ConfigMap
metadata:
  name: mysub-config
data:
  SERVER_PORT: "8080"
  POSTGRES_HOST: "postgres-mysub-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "mysub"
  POSTGRES_USER: "admin"
  FEE_LEVEL_COLLECTOR: "50000"
  FEE_LEVEL_ADDICT: "100000"
